[package]
name = "the_bob"
version = "0.1.0"
authors = ["Magnus Lechner <mlechner111@gmail.com>"]

[dependencies]
config = "0.9"
hyper = "0.12"
hyper-tls = "0.3.1"
serde = "1.0.79"
serde_json = "1.0"
serde_derive = "1.0.79"